---
- hosts: prod-server
  become: true

  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker
  
  - name: stop and remove existing healthcare container
    command: sudo docker rm -f healthcare 
    
  - name: deploy healthcare application
    command: sudo docker run -itd -p 8082:8082 --name  healthcare vidyadhare/healthcare:1.0
